### ISSUE TITLE
snapshot_url or vignette_url attributes no more available after upgrade to 1.5

### ISSUE THREAD

**Issue by marcob79** [k-the-hidden-hero/bticino_intercom#6]
With previous version, snapshot_url and vignette_url attributes were present together with 1 sensor entity available in home assistant.
After 1.5 upgrade, I'm no more able to see it in any sensor (not sure if somehow linked to other issue #5 )
I also checked events, and also looking over there, I didn't see such information

```
Executed: May 4, 2025 at 16:05:47
this:
  entity_id: automation.notifica_citofono
  state: 'on'
  attributes:
    id: '1745494441587'
    last_triggered: '2025-04-30T20:13:11.960681+00:00'
    mode: parallel
    current: 0
    max: 10
    friendly_name: notifica citofono
  last_changed: '2025-05-02T11:39:26.889591+00:00'
  last_reported: '2025-05-02T11:39:26.889591+00:00'
  last_updated: '2025-05-02T11:39:26.889591+00:00'
  context:
    id: 01JT8CPN99VZEBAW9GF6V75H1E
    parent_id: null
    user_id: null
trigger:
  id: '1'
  idx: '1'
  alias: null
  platform: event
  event:
    event_type: bticino_intercom_incoming_call
    data:
      name: Incoming Call (Classe 100X16E)
      module_id: 00:03:50:ce:00:59
    origin: LOCAL
    time_fired: '2025-05-04T14:05:47.156682+00:00'
    context:
      id: 01JTDSW1RM029PQR31FX1VFDFV
      parent_id: null
      user_id: null
  description: event 'bticino_intercom_incoming_call'
```
